apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: develop
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /products/
            pathType: Prefix
            backend:
              service:
                name: productssvc
                port:
                  number: 80
                  

