name: Backend CD Pipeline (EKS)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        type: string
      namespace:
        description: 'Kubernetes namespace to deploy to'
        required: false
        default: default
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux, qa]

    env:
      ECR_REPOSITORY: ecommerce-backend
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set ECR Registry as ENV
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Update Deployment image
        working-directory: app/backend-src/k8s
        run: |
          sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.image_tag }}|" Deployment.yml

      - name: Apply Kubernetes manifests
        working-directory: app/backend-src/k8s
        run: |
          kubectl apply -n ${{ inputs.namespace }} -f Deployment.yml
          kubectl apply -n ${{ inputs.namespace }} -f Ingress.yml
          
