name: Backend CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'app/backend-src/**'
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  AWS_DEFAULT_REGION: ap-south-1
  ECR_REPOSITORY: ecommerce-backend
  SONAR_PROJECT_KEY: chandrakatore2004_ecommerce-backend

jobs:
  backend-ci:
    runs-on: [self-hosted, linux, qa]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set image tag variables
        id: meta
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          SAFE_REPO=$(echo "${GITHUB_REPOSITORY}" | tr '/' '-')
          IMAGE_TAG="${SAFE_REPO}-${SHORT_SHA}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY" >> $GITHUB_ENV
          echo "::set-output name=image_tag::$IMAGE_TAG"

      - name: SonarCloud scan with Maven
        working-directory: app/backend-src
        run: |
          chmod +x ./mvnw
          ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=chandrakatore2004 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Wait for SonarCloud Quality Gate result
        working-directory: app/backend-src
        run: |
          echo "Waiting for SonarCloud analysis to complete..."
          sleep 10

          if [[ ! -f target/sonar/report-task.txt ]]; then
            echo "ERROR: report-task.txt not found."
            exit 1
          fi

          ANALYSIS_ID=$(grep ceTaskId target/sonar/report-task.txt | cut -d= -f2)
          if [[ -z "$ANALYSIS_ID" ]]; then
            echo "ERROR: Analysis ID not found."
            exit 1
          fi

          echo "Got Analysis ID: $ANALYSIS_ID"

          for i in {1..30}; do
            STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
              "https://sonarcloud.io/api/ce/task?id=$ANALYSIS_ID" | jq -r '.task.status')
            echo "Status: $STATUS"
            [[ "$STATUS" == "SUCCESS" ]] && break
            sleep 10
          done

          curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ env.SONAR_PROJECT_KEY }}" \
            | tee quality-gate-response.json

          PROJECT_STATUS=$(jq -r '.projectStatus.status' quality-gate-response.json)
          echo "Quality Gate Status: $PROJECT_STATUS"

          if [[ "$PROJECT_STATUS" != "OK" ]]; then
            echo "Quality Gate failed"
            exit 1
          else
            echo "Quality Gate passed"
          fi

      - name: Build, scan, tag, and push Docker image
        working-directory: app/backend-src
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY
          echo "Building Docker image with tags: $IMAGE_TAG and latest"
          docker build -t $IMAGE_URI:$IMAGE_TAG -t $IMAGE_URI:latest .

          echo "Scanning image with Trivy (HIGH/CRITICAL)"
          trivy image --exit-code 1 --severity CRITICAL --no-progress $IMAGE_URI:$IMAGE_TAG

          echo "Pushing Docker image to ECR"
          docker push $IMAGE_URI:$IMAGE_TAG
          docker push $IMAGE_URI:latest

      - name: Trigger CD Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Backend CD Pipeline (EKS)
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
          inputs: '{"image_tag": "${{ steps.meta.outputs.image_tag }}"}'
