name: Backend CI Pipeline
on:
  push:
    branches:
      - master
    paths:
      - 'app/backend-src/**'
  workflow_dispatch:

jobs:
  backend-ci-cd:
    runs-on: [self-hosted, linux, qa]  # Your self-hosted runner labels

    env:
      AWS_REGION: ap-south-1
      ECR_REPOSITORY: ecommerce-backend
      IMAGE_TAG: ${{ github.run_id }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name:  Make mvnw executable
        run: chmod +x app/backend-src/mvnw

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        working-directory: app/backend-src
        run: ./mvnw clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        working-directory: app/backend-src
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EKS
      if: false  
      run: |
          sed -i "s|<IMAGE_TAG>|${{ env.IMAGE_TAG }}|g" app/backend-src/k8s/Deployment.yml
          kubectl apply -f app/backend-src/k8s/Deployment.yml
