name: CloudFront - Deploy Static Website from S3

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  WORK_DIR: CloudFront/solar-system
  AWS_REGION: us-east-1
  AWS_S3_BUCKET: cloudfront-solar-systems

jobs:
  deploy:
    runs-on: [self-hosted, linux, qa]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Authenticate to AWS via OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::355511498283:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      # Sync files to S3
      - name: Sync files to S3
        run: |
          aws s3 sync ${{ env.WORK_DIR }} s3://${{ env.AWS_S3_BUCKET }} --region ${{ env.AWS_REGION }} --delete

      # Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
