name: Deploy Static Website to S3 + CloudFront

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  WORK_DIR: CloudFront/solar-system
  AWS_REGION: ap-south-1
  AWS_S3_BUCKET: cloudfront-solar-system

jobs:
  deploy:
    runs-on: [self-hosted, linux, qa]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Optional: If you have a build step (npm run build), enable Node
      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # - name: Install dependencies
      #   run: npm install --prefix $WORK_DIR
      #
      # - name: Build project
      #   run: npm run build --prefix $WORK_DIR

      - name: Sync files to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: ${{ env.AWS_S3_BUCKET }}
          region: ${{ env.AWS_REGION }}
          source-dir: ${{ env.WORK_DIR }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        with:
          distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
