jobs:
  deploy-to-eks:
    runs-on: [self-hosted, linux, qa]
    workflow_dispatch:
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubeconfig for EKS
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name AWS_SECRET_EKS_CLUSTER_NAME

      - name: Deploy to EKS
        run: |
          kubectl apply -f app/backend-src/k8s/Deployment.yml


      