name: Frontend CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'app/frontend-src/**'
  workflow_dispatch:

jobs:
  frontend-ci:
    runs-on: [self-hosted, linux, qa]

    env:
      AWS_REGION: ap-south-1
      ECR_REPOSITORY: ecommerce-frontend

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set image tag variables
        id: meta
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          SAFE_REPO=$(echo "${GITHUB_REPOSITORY}" | tr '/' '-')
          IMAGE_TAG="${SAFE_REPO}-${SHORT_SHA}"
