name: 'Initialize MySQL Tables & Data'

on:
  workflow_dispatch: {}  # Manual trigger
  workflow_run:          # Trigger after "Terraform Infrastructure Pipeline" completes successfully
    workflows: ["Terraform Infrastructure Pipeline"]
    types:
      - completed

jobs:
  init-db:
    name: Initialize MySQL Tables & Data
    runs-on: qa  # self-hosted runner
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Connect to MySQL and run SQL script
        env:
          DB_HOST: ${{ secrets.RDS_ENDPOINT }}
          DB_PORT: 3306
          DB_USER: ${{ secrets.RDS_USERNAME }}
          DB_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: |
          echo "Waiting for RDS to be ready..."
          sleep 60
          echo "Running SQL script against RDS at $DB_HOST"
          mysql -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASSWORD" < db/DB_Queries.sql
