name: Playwright CI

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'playwright_automation/**'

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  playwright-tests:
    runs-on: [self-hosted, linux, qa]

    defaults:
      run:
        working-directory: playwright_automation

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: playwright_automation/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright_automation/playwright-report
