name: Playwright CI

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'playwright_automation/**'

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  playwright-tests:
    runs-on: [self-hosted, linux, qa]

    defaults:
      run:
        working-directory: playwright_automation

    env:
      TEST_ENVIRONMENT: dev
      CLAS_WEB_URL: ${{ secrets.CLAS_WEB_URL }}
      CLAS_USERNAME: ${{ secrets.CLAS_USERNAME }}
      CLAS_PASSWORD: ${{ secrets.CLAS_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false # avoid EACCES issues

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: playwright_automation/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Load local env if present
        if: ${{ runner.os != 'Linux' }} # local dev only
        run: |
          if [ -f "./env/dev.env" ]; then
            echo "Loading local env vars..."
            export $(grep -v '^#' ./env/dev.env | xargs)
          fi

      - name: Run Playwright tests
        run: npx playwright test --reporter=list

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright_automation/playwright-report
