name: CI/CD workflow for SonarCloud Code Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, qa]  # Ensure EC2 runner has these labels

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Required for SonarCloud blame info

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -f Project-3/MyWebApp/pom.xml

      - name: SonarCloud Scan (via Maven plugin)
        working-directory: Project-3/MyWebApp
        run: >
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar 
          -Dsonar.projectKey=chandrakatore2004_aws-eks-3tier-devops-demo 
          -Dsonar.organization=chandrakatore2004 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
          

      - name: SonarCloud Quality Gate check
        id: sonarcloud-quality-gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
