name: CI/CD workflow for SonarCloud Code Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, qa]  # Ensure EC2 runner has these labels

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -f Project-3/MyWebApp/pom.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: Project-3/MyWebApp
          args: >
            -Dsonar.projectKey=chandrakatore2004_aws-eks-3tier-devops-demo
            -Dsonar.organization=chandrakatore2004
         


      - name: SonarCloud Quality Gate check
        id: sonarcloud-quality-gate
        uses: sonarsource/sonarqube-quality-gate-action@master
      
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}



  
