name: CI/CD workflow for SonarCloud Code Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: [self-hosted, linux, qa]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install
        working-directory: Project-3/MyWebApp

      - name: Run SonarCloud Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=chandrakatore2004_aws-eks-3tier-devops-demo \
            -Dsonar.organization=chandrakatore2004 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: Project-3/MyWebApp

      - name: Copy report-task.txt to root for Quality Gate check
        run: cp Project-3/MyWebApp/.scannerwork/report-task.txt report-task.txt

      - name: SonarCloud Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: report-task.txt
          pollingTimeoutSec: 300
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
