name: WordPress Deploy Themes

# Triggers
on:
  push:
    branches:
      - main
    paths:
      - 'wordpress/wp-content/themes/**'   # Trigger for any theme changes
  workflow_dispatch:  # Manual trigger

# Permissions for OIDC
permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1  # Set your AWS region

jobs:
  deploy:
    runs-on: [self-hosted, linux, qa]

    steps:
      # Step 1: Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials (OIDC)
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Get WordPress pod name
      - name: Get WordPress Pod
        id: get_pod
        run: |
          POD=$(kubectl get pods -n default -l app.kubernetes.io/name=wordpress -o jsonpath="{.items[0].metadata.name}")
          echo "WORDPRESS_POD=$POD" >> $GITHUB_ENV

      # Step 4: Sync all themes
      - name: Sync WordPress Themes
        run: |
          echo "Syncing themes to WordPress pod..."
          kubectl exec -n default $WORDPRESS_POD -- mkdir -p /bitnami/wordpress/wp-content/themes
          rsync -av --delete wordpress/wp-content/themes/ default/$WORDPRESS_POD:/bitnami/wordpress/wp-content/themes/
          kubectl exec -n default $WORDPRESS_POD -- chown -R 1001:1001 /bitnami/wordpress/wp-content/themes/

      # Step 5: Restart WordPress pod to apply changes
      - name: Restart WordPress Pod
        run: |
          kubectl rollout restart deployment wp-wordpress -n default
