apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
  namespace: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: 596169662054.dkr.ecr.ap-south-1.amazonaws.com/solar-system:solar-system-16604983692-0f61203
        imagePullPolicy: Always
        name: solar-system
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        # envFrom:
        # - secretRef:
        #     name: mongo-db-creds